### ISSUE TITLE
Typography syntax error

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/senf-atomic-design-system#91]
<img width="888" alt="Bildschirmfoto 2022-05-05 um 12 18 40" src="https://user-images.githubusercontent.com/49417005/166912814-77d17998-bca0-4ca6-9c3e-52b76101fc7c.png">

**Comment by Enjoy2Live** [comment]
would you please elaborate on this please? I've worked on typography so it might be easier for me to fix it!
